name: deploy-cloud-run
on:
  - workflow_dispatch
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CLOUDRUN_SA_KEY }}
          export_default_credentials: true
      - name: Verify gclouds
        run: gcloud info

      - name: Deploy cloud-run
        id: deploy
        uses: GoogleCloudPlatform/github-actions/deploy-cloudrun@master
        with:
          image: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-microservice
          service: flask-helloworld
          region: asia-northeast1
      - name: Verify
        run: curl ${{ steps.deploy.outputs.url }}
